### ISSUE TITLE
Insight post formatting with long URLs

### ISSUE THREAD

**Issue by Techneaux** [ocelotconsulting/ocelotconsulting.github.io#130]
![image](https://user-images.githubusercontent.com/8344081/234085293-279e6acc-12aa-40f1-a76c-9384a47df17e.png)

Long URLs in mobile safari cause the default page zoom to be wacky.

https://www.ocelotconsulting.com/insights/state-of-devops-2022-the-j-curve

**Comment by PMByrne** [comment]
...making me break out XCode for this one...
