### ISSUE TITLE
Arrow buttons on case-studies page

### ISSUE THREAD

**Issue by mike-weaver** [ocelotconsulting/ocelotconsulting.github.io#133]
The right and left arrow buttons to scroll through the case studies are not functional. They should scroll indefinitely and loop around like the buttons on the home page to scroll through the "Our best sales pitch is our track record of success" cards. Instead, these stop with one click to the right, and then clicking back to the left doesn't do anything.

![Screenshot 2023-04-24 at 1 44 43 PM](https://user-images.githubusercontent.com/48367929/234087966-6e28faa7-802b-4734-91b9-979d6f99707f.png)

**Comment by nerddtvg** [comment]
`Because of nature of how the loop mode works (it will rearrange slides), total number of slides must be >= slidesPerView * 2`

We don't have enough slides.

**Comment by mike-weaver** [comment]
Is there any way to fix this other than writing a bunch of new case studies?

**Comment by nerddtvg** [comment]
I'm going to disable loop when we don't have enough, that way it at least doesn't break going backwards and look weird.

**Comment by PMByrne** [comment]
I guess the other option is we could just duplicate the cards once if `# cards < slidesPerView * 2`
