### ISSUE TITLE
Stylesheet hides list numbers and bullets

### ISSUE THREAD

**Issue by nerddtvg** [ocelotconsulting/ocelotconsulting.github.io#148]
Top level lists have their numbers and bullets hidden. Sub-lists do not.

Example: https://www.ocelotconsulting.com/insights/randomize-slack

![image](https://user-images.githubusercontent.com/5490719/234374928-e0cf4851-eb88-4bb8-9f8e-84edc5cfda98.png)

**Comment by PMByrne** [comment]
I think this solves the problem:  https://tailwindcss.com/docs/typography-plugin
