### ISSUE TITLE
Fix Inline Images and Styles

### ISSUE THREAD

**Issue by nerddtvg** [ocelotconsulting/ocelotconsulting.github.io#149]
Some images from the old blogs used attribute overrides to set to `display:inline-block` but the new MDX import does not support attributes like that. Need to find a way to resolve this. Was looking into rehype-attr but it doesn't support `mdxTextExpression` as a source type. `remark-attr` doesn't seem to work either. Not sure our options or if we should use JSX / a component to achieve this.

https://www.ocelotconsulting.com/insights/randomize-slack

https://www.ocelotconsulting.com/insights/randomize-twitter

This would also be applicable for `.post-center` classes from old posts where we tried to center the images and captions.

**Comment by PMByrne** [comment]
Just import and use [next/image](https://nextjs.org/docs/api-reference/next/image) and a class of `inline-block`

**Comment by nerddtvg** [comment]
Doesn't that defeat the purpose of using Markdown and keeping it cleaner? Plus, it doesn't solve the captions underneath images nor fix the other HTML items that may need to be centered.
