### ISSUE TITLE
Horizontal scrolling issues on mobile

### ISSUE THREAD

**Issue by PMByrne** [ocelotconsulting/ocelotconsulting.github.io#27]
**Describe the bug**
Scrolling around on any page causes a vertical gray bar to be visible on the right side of the screen

**To Reproduce**
1. Pick a page and swipe horizontally 

**Expected behavior**
There should be no horizontal motion

**Screenshots**
![4E112004-4E6A-4F9B-8880-C409500D9929](https://user-images.githubusercontent.com/6628400/82104051-fa9f4400-96da-11ea-85cf-3d03e6003a74.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: 13
 - Browser: Safari

**Additional context**
Video in slack

**Comment by Techneaux** [comment]
Known issue with Bulma affecting the column class https://github.com/jgthms/bulma/issues/2242.
Trying out one of the suggested fixes which is to use the is-gapless option.
Other suggested fixes look to affect accessibility.
