### ISSUE TITLE
Duplicate Nav for Services & Success Stories/Industries

### ISSUE THREAD

**Issue by larryboymi** [ocelotconsulting/ocelotconsulting.github.io#31]
**Describe the bug**
Duplicate Services and Success Stories/Industries sections. They appear on both the main single page as well as a landing page for both under the nav. My suggestion would be to collapse them into the main single page, with the preferred look/feel between the 2.

**To Reproduce**
1. Go to main page, see "Services" Section
2. Click on "What we Do" -> Services
3. Scroll down to content
4. See 2nd version of headings

<repeat for Success Stories/Industries>

**Expected behavior**
A single rollup for both things (Services and Success Stories/Industries).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX (but any)
 - Browser: Chrome (but any)

**Comment by Techneaux** [comment]
Like this call-out. What if we keep the services titles on the main page like today BUT we standardize the titles across the pages.

So: main page is "here's a list of the services we offer"
Then you go into services page "here's the details on the services" (we change this page from today where the services titles and order don't match the main page)
Finally there's a link in the services page to the industries page "and hey go here and you can learn what specifically we did with these services!" (need to add this link)
