### ISSUE TITLE
Minor Cosmetic Improvements

### ISSUE THREAD

**Issue by patrickrgaffney** [ocelotconsulting/ocelotconsulting.github.io#40]
From Nick Weaver:

> I’ve looked through the new Ocelot website, and it looks really good! I wanted to suggest a few small changes I think could make usability and navigability much easier for users. Some of these are my opinions, but others I think would make a big difference. Please let me know what you think.
> 
> - [ ] Change "Expert Solutions, Built Together" to "Partners In Innovation"
> - [ ] Change "What makes Ocelot an exceptional partner for your business?" to "Expert Solutions, Built Together"
> - [ ] Change "How we work" to "Our Team"
> - [x] Add "Meet The Ocelots" page to a tab under "Who We Are" on the main navigation
> - [x] Decrease the font size significantly on the Meet The Ocelots page and choose a less bold font for those paragraphs. Left align instead of center align. then, break up big chunks of text like under the "Our People" section into multiple paragraphs.
> - [ ] Change "Learn more about the industries we serve" button to simply "Learn More"
> - [ ] Make all the social links at the bottom of the website open in new tabs.
> - [x] Decrease the font size on the individual industry pages to make reading them easier.
> - [x] Replaces the word "Blog" with the word "Insights" or "Thoughts" which are industry standard.
> - [ ] Add share buttons to the bottom of each blog.

We could move this out into separate issues as needed or as some of these are resolved.

**Comment by Techneaux** [comment]
If no objections, think I'll separate out into a new issue the "share buttons" for the blog posts and keep the rest in this issues. The rest are quick minor fixes while the share buttons is a little bit more effort/new feature.

**Comment by patrickrgaffney** [comment]
Sounds good to me. 👍
