### ISSUE TITLE
LICENSE file for the repo

### ISSUE THREAD

**Issue by philcryer** [ocelotconsulting/ocelotconsulting.github.io#44]
It's tradition to have a LICENSE file at the base of a github repo, does Ocelot have a license in mind for its site code? As an example: [LICENSE](https://github.com/philcryer/fak3r.com/blob/master/LICENSE)

GitHub resources: [Licensing a repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) and [Choose a license](https://choosealicense.com/)

**Comment by Techneaux** [comment]
@philcryer what license would you recommend? MIT?

**Comment by philcryer** [comment]
I would, but I was contacted out of band that the project was not meant to have a LIC - don't know the reasoning, also don't know why they didn't close this if they didn't want one.

--
http://philcryer.com / 04A1 69CC A79F 7188

**Comment by Techneaux** [comment]
I see that conversation now. If we are going to reserve all rights, as you said I do suggest we close this issue. I can close it if no one has other thoughts.
