### ISSUE TITLE
Add subtitles for those missing them on https://www.ocelotconsulting.com/posts/

### ISSUE THREAD

**Issue by timotab** [ocelotconsulting/ocelotconsulting.github.io#63]
Add subtitles for those missing them on https://www.ocelotconsulting.com/posts/

Nick's post of 7/17/2020: "Show Don't Tell"
Artem's post of 8/15/2019: (subtitle TBD)
Artem's post of 2/25/2019: (subtitle TBD)
John's post of 2/21/2019: (subtitle TBD)

Also fix capitalisation of Kara's post of 7/11/2020

**Comment by nerddtvg** [comment]
@PMByrne mentioned in the channel he would like to change the subtitles of posts to not be in the header or possibly remove them entirely.
