### ISSUE TITLE
Add links to additional social media pages

### ISSUE THREAD

**Issue by CathyC93** [ocelotconsulting/ocelotconsulting.github.io#68]
At the bottom of the site, we currently have links to our GitHub, LinkedIn, etc.  It might be nice to add links to our YouTube, Instagram, or any other pages we plan to keep updated and might be useful for people checking out Ocelot.

**Comment by CathyC93** [comment]
Whoops, didn't see you self-assigned this, @patrickrgaffney 😅
I will open another story for embedding YouTube links and tag you over there

**Comment by patrickrgaffney** [comment]
No worries! When we were talking about it on the call I just self-assigned this one so I'd see it on the landing page later (when I inevitably forgot about it). 💯
