### ISSUE TITLE
CSS class usage for body optimization

### ISSUE THREAD

**Issue by Techneaux** [ocelotconsulting/ocelotconsulting.github.io#96]
We currently use the `.highlight` class for the body instead of the `.content` class, which causes some issues including poor list alignment. We can't just simply switch over because that would break the header and footer overlays. But some work to optimize class usage here would eliminate the need for other temporary fixes (like #94).

https://bulma.io/documentation/elements/content/

**Comment by nerddtvg** [comment]
From #101:

This is an initial fix for #96 where we reinstate the .content wrapper around blog posts (posts.html). This change required fixing the _highlights.css file to only change the font-color for the .welcome-text classes and not the entire element. It also impacted how the menu on the /industries/ page loaded where the bullets were showing again. That was removed and extra padding was added to the li items to recreate the original spacing look.

The main changes for the blog posts are:

Extra whitespace around headers, it's easier to read
Removed the post-list-fix hack from before
Besides the whitespace, nothing else should be visibly different between the entries. A/B comparisons were done using a local build and tabbing back and forth from the production website.

All primary non-blog pages were tested with no other changes besides the industries menu as mentioned.

This does not complete #96, we should still review the CSS and see if we can't keep Bulma upgraded without breaking the site.
